//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ase77146774_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bugs_tbl
    {
        public int id { get; set; }
        public string prod_name { get; set; }
        public string bug_name { get; set; }
        public string bug_desc { get; set; }
        public string syntax { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
